name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: "12.x"
          distribution: "adopt"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.4"
          
      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > ${{ github.workspace }}/android/release.keystore

      - name: Decode key.properties
        run: echo "${{ secrets.KEY_PROPERTIES }}" | base64 --decode > ${{ github.workspace }}/android/key.properties

      

      - name: Check Keystore File
        run: |
          if [[ -f ${{ github.workspace }}/android/release.keystore ]]; then
            echo "Keystore file found."
          else
            echo "Keystore file not found."
            exit 1
          fi

      - name: Build App Bundle
        run: flutter build appbundle --release

      - name: Decode Service Account JSON
        run: echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" | base64 --decode > ${{ github.workspace }}/service-account.json

      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ github.workspace }}/service-account.json
          packageName: com.wildlifeconnect.app
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal
