name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: "12.x"
          distribution: "adopt"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.x"

      - name: Decode Keystore
        run: echo ${{ secrets.KEYSTORE }} | base64 -d > android/app/release.keystore

      - name: Build App Bundle
        run: flutter build appbundle --release

      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.example
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal
